### PR TITLE
Use strict data model checks with pydantic

### PR DESCRIPTION
**Pull request by kdeyev**
pyonwater version is updated

### CODE REVIEW

**Comment by disforw** [comment]
Why are you adding the names back in tot he entity description? Having hardcoded names is no longer allowed on new integrations. The names (if manually added) need to be added via the strings file using the translated_key.

**Comment by kdeyev** [comment]
Got it, will fix

**Comment by kdeyev** [comment]
@disforw I've generated data models for pyonwater:https://github.com/kdeyev/pyonwater/blob/v0.2.1/pyonwater/models/eow_models.py
It should make it easier to maintain/extend the code base

**Comment by kdeyev** [comment]
Tested with [v2.1.0-alpha.1](https://github.com/kdeyev/eyeonwater/releases/tag/v2.1.0-alpha.1)

**Comment by kdeyev** [comment]
Ready for review

**Comment by disforw** [comment]
HA will not accept a new integration with description names hardcoded. I'll post documentation. The translation_key will lookup the name (if required) in the strings file. Some entities do not need a name because HA will auto determine the name from the class used.

**Comment by disforw** [comment]
Also, I used the "key" with proper case to match the actual flag because core doesn't care about case in the key

**Comment by disforw** [comment]
https://developers.home-assistant.io/blog/2022/07/10/entity_naming/

Also see:
https://developers.home-assistant.io/docs/core/entity/#entity-naming

**Comment by disforw** [comment]
I'd remove all the names, revert all the keys and change line 110 back to use description.key

**Comment by kdeyev** [comment]
Hey @disforw . Sorry for the misunderstanding.
The name is not used: in the BinarySensorEntityDescription:
```
        self.entity_description = BinarySensorEntityDescription(
            key=description.key,
            device_class=description.device_class,
            translation_key=description.translation_key,
        )
```
The name is only used for the unique_id generation here:
```
self._attr_unique_id = f"{description.name}_{self.meter.meter_uuid}"
```
The latest version of pyonwater uses snake_case for attributes and all the changes you see here are made to support it.
Please let me know if you still see a problem.

**Comment by kdeyev** [comment]
I could use the key here:
```
self._attr_unique_id = f"{description.key}_{self.meter.meter_uuid}"
```
But then unique_id will be changed, If it's not a concern I can easily do that

**Comment by disforw** [comment]
Ah, I see what you did now... Do you think it adds a layer of unnecessary complexity?
I mean, when creating binary_sensor.py, I used the "best practices" that I've seen in other integrations. It's up to you.
When we submit to core, we can see what they say about it then.

**Pull request merged**
