### PR TITLE
Remove/unit of measurement

### PR DESCRIPTION
**Pull request by disforw**
This PR will remove all need for us to determine what to display for the user. By reading the unit given to us by the API and telling HA what the NATIVE reading is, HA will automatically calculate and display the proper unit to the user.

### CODE REVIEW

**Comment by kdeyev** [comment]
You may want to install pre-commit on your local dev environment. It will fix minor code styling issued before the commit, so the git pipeline will not fail then.

**Comment by disforw** [comment]
Interestingly, I don’t usually work out of a “dev environment”. Most of my “play time” is spent on my ipad while sitting right on the couch. 🙈 I hope thats OK. I’ll try and work more in a teamate fashion using branches and PRs instead of straight master branch editing….

**Comment by kdeyev** [comment]
No problem at all, working from the browser should not be a problem.
I meant the GitHub check failures. The checks are mostly complaining about minor issues like extra space somewhere or unused import.
Let me think If I can fix it automatically since you are working from the browser.

**Comment by disforw** [comment]
Working this in #64

**Pull request closed without merging**
